[phases.setup]
nixPkgs = ["...", "nodejs_22", "python3"]
aptPkgs = ["...", "ffmpeg"]

[phases.install]
cmds = [
  "npm install",
  "YTDLP_URL=https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux node node_modules/@distube/yt-dlp/script/download.js"
]

[phases.build]
cmds = ["ffmpeg -version", "npm run build"]

[start]
cmd = "npm start"
