import {
  ChannelType,
  EmbedBuilder,
  PermissionFlagsBits,
  type Client,
  type Guild,
  type GuildMember,
  type Invite,
  type TextChannel
} from "discord.js";
import type { Env } from "../config/env.js";
import { logger } from "../utils/logger.js";

const DEFAULT_INVITE_LOG_CHANNEL_ID = "1503931843127541842";
const inviteUsesByGuild = new Map<string, Map<string, number>>();

function resolveLogChannelId(env: Env): string {
  return env.INVITE_LOG_CHANNEL_ID ?? DEFAULT_INVITE_LOG_CHANNEL_ID;
}

async function resolveInviteLogChannel(guild: Guild, env: Env): Promise<TextChannel | null> {
  const channelId = resolveLogChannelId(env);
  const channel = guild.channels.cache.get(channelId) ?? (await guild.channels.fetch(channelId).catch(() => null));

  if (!channel || channel.type !== ChannelType.GuildText) {
    logger.warn({ guildId: guild.id, channelId }, "Invite log channel not found or not a text channel");
    return null;
  }

  return channel as TextChannel;
}

function buildUsesMap(invites: Iterable<Invite>): Map<string, number> {
  const map = new Map<string, number>();
  for (const invite of invites) {
    map.set(invite.code, invite.uses ?? 0);
  }
  return map;
}

async function fetchGuildInvites(guild: Guild): Promise<Map<string, Invite> | null> {
  const me = guild.members.me ?? (await guild.members.fetchMe().catch(() => null));
  if (!me?.permissions.has(PermissionFlagsBits.ManageGuild)) {
    logger.warn({ guildId: guild.id }, "Cannot fetch invites: missing ManageGuild permission");
    return null;
  }

  const invites = await guild.invites.fetch().catch((error) => {
    logger.warn({ err: error, guildId: guild.id }, "Failed to fetch guild invites");
    return null;
  });

  return invites ?? null;
}

export async function primeInviteCacheForGuild(guild: Guild): Promise<void> {
  const invites = await fetchGuildInvites(guild);
  if (!invites) {
    return;
  }

  inviteUsesByGuild.set(guild.id, buildUsesMap(invites.values()));
}

export async function primeInviteCaches(client: Client): Promise<void> {
  for (const guild of client.guilds.cache.values()) {
    await primeInviteCacheForGuild(guild);
  }
}

export function registerInviteInCache(invite: Invite): void {
  const guildId = invite.guild?.id;
  if (!guildId) {
    return;
  }

  const current = inviteUsesByGuild.get(guildId) ?? new Map<string, number>();
  current.set(invite.code, invite.uses ?? 0);
  inviteUsesByGuild.set(guildId, current);
}

export function removeInviteFromCache(invite: Invite): void {
  const guildId = invite.guild?.id;
  if (!guildId) {
    return;
  }

  const current = inviteUsesByGuild.get(guildId);
  if (!current) {
    return;
  }

  current.delete(invite.code);
}

export async function logInviteGenerated(input: {
  env: Env;
  guild: Guild;
  invite: Invite;
  generatedByUserId: string;
  generatedByTag: string;
}): Promise<void> {
  const channel = await resolveInviteLogChannel(input.guild, input.env);
  if (!channel) {
    return;
  }

  registerInviteInCache(input.invite);

  const embed = new EmbedBuilder()
    .setColor(0x57f287)
    .setTitle("Invite Generated")
    .addFields(
      { name: "Generated By", value: `<@${input.generatedByUserId}> (${input.generatedByTag})`, inline: false },
      { name: "Invite", value: input.invite.url, inline: false },
      { name: "Code", value: input.invite.code, inline: true },
      { name: "Timestamp", value: `<t:${Math.floor(Date.now() / 1_000)}:F>`, inline: true }
    )
    .setTimestamp();

  await channel.send({ embeds: [embed] }).catch((error) => {
    logger.error({ err: error, guildId: input.guild.id, channelId: channel.id }, "Failed to send invite generated log");
  });
}

export async function logInviteUsedByMemberJoin(member: GuildMember, env: Env): Promise<void> {
  const guild = member.guild;
  const channel = await resolveInviteLogChannel(guild, env);
  if (!channel) {
    return;
  }

  const invites = await fetchGuildInvites(guild);
  if (!invites) {
    return;
  }

  const previousUses = inviteUsesByGuild.get(guild.id) ?? new Map<string, number>();
  let usedInvite: Invite | null = null;

  for (const invite of invites.values()) {
    const previous = previousUses.get(invite.code) ?? 0;
    const current = invite.uses ?? 0;
    if (current > previous) {
      usedInvite = invite;
      break;
    }
  }

  inviteUsesByGuild.set(guild.id, buildUsesMap(invites.values()));

  const embed = new EmbedBuilder().setColor(0x5865f2).setTitle("Invite Used").setTimestamp();

  if (usedInvite) {
    const inviterText = usedInvite.inviter ? `<@${usedInvite.inviter.id}> (${usedInvite.inviter.tag})` : "Unknown";

    embed.addFields(
      { name: "Joined User", value: `<@${member.id}> (${member.user.tag})`, inline: false },
      { name: "Invite", value: usedInvite.url, inline: false },
      { name: "Code", value: usedInvite.code, inline: true },
      { name: "Inviter", value: inviterText, inline: true },
      { name: "Timestamp", value: `<t:${Math.floor(Date.now() / 1_000)}:F>`, inline: false }
    );
  } else {
    embed
      .setColor(0xfee75c)
      .setDescription("A member joined, but the used invite could not be resolved (possibly vanity URL or missing cache baseline).")
      .addFields(
        { name: "Joined User", value: `<@${member.id}> (${member.user.tag})`, inline: false },
        { name: "Timestamp", value: `<t:${Math.floor(Date.now() / 1_000)}:F>`, inline: false }
      );
  }

  await channel.send({ embeds: [embed] }).catch((error) => {
    logger.error({ err: error, guildId: guild.id, channelId: channel.id }, "Failed to send invite used log");
  });
}
